# netlify.toml
[build]
  publish = "public"
  command = "hugo --minify"

[context.production.environment]
  HUGO_VERSION = "0.147.0"  # 使用中のHugoバージョンをここに指定

[context.deploy-preview.environment]
  HUGO_VERSION = "0.147.0"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.147.0"

